### ISSUE TITLE
Any chance there is a Roadmap for the WB ?

### ISSUE THREAD

**Issue by luzpaz** [rostskadat/FreeCAD-SH3D#4]
Are you planning to have a roadmap or use the repository milestone method (assigning tickets to each milestone) ? 

- [ ] https://github.com/rostskadat/FreeCAD-SH3D/issues/5
- [ ] Documentation

**Comment by rostskadat** [comment]
Hello @luzpaz 

I have no roadmap so far, but I'm totally opened to establish one. 
If you happen to have suggestions about the workflow that should be established, please feel free to let me know.

Regards

**Comment by luzpaz** [comment]
Some ideas:  
- [ ] Ability to support materials assigned in SH3D within FreeCAD (basically ability to recognize the SH3D's various libraries of materials, furniture, mannequins etc...)
- [ ] Importing landscapes around models (SH3D is known for their elaborate user [showcases](https://www.sweethome3d.com/gallery.jsp))  

cc @yorikvanhavre (any ideas?)

**Comment by rostskadat** [comment]
Hello,

@luzpaz  @yorikvanhavre, I just saw that there already is a `importSH3D` in the BIM workspace.
I did not realize that was the case. Maybe this workbench is redundant and should be folded back into the BIM workbench and the function there expanded if need be. That would definitely be less confusing for the User (i.e. should I use "the import function of the BIM WB" or "the import function of the SH3D workbench")

What do you think?

**Comment by yorikvanhavre** [comment]
There is never such thing as "too many tools for the same thing" in FreeCAD :) Different solutions are always beneficial to the user. So feel free to keep working on your own solution!

The SH3D importer in FreeCAD is rather old and not well maintained, I'm not even sure it still works... 

I think you are the best person to know what's best to do here, @rostskadat . Would you rather keep working on your version? Does it work better than the built-in one in BIM? Would you rather have your merged there?

**Comment by rostskadat** [comment]
Hello @yorikvanhavre ,

I think that:
1. for basic feature such as import/export a standard implementation is better than several ones (from the user perspective)
2. in the case of SH3D, there are not so many real features beyond importing (/ exporting ???). 
3. I did use it in conjunction with the Arch WB, which make me believe the BIM WB is probably the best place for such functionality.

Therefore I think that folding this WB into the existing BIM code, would be preferable. 
If you don't mind, I will fork that workbench and rework the old import function to integrate the new code.

**Comment by rostskadat** [comment]
Hello @yorikvanhavre  @luzpaz ,

I have migrated the importer to the BIM WB. The changes are in my FreeCAD fork. 
I will try to get the merge included there. If you don't mind I will therefore close that issue.
Once merged I'll archive that repo and remove it from the Wiki.

Regards
